# Generated by Django 4.2.4 on 2023-09-17 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Problem', '0002_alter_problem_difficulty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='score',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='testcases',
        ),
    ]
