# Generated by Django 4.2.4 on 2023-09-27 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Problem', '0004_alter_problem_difficulty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testcase',
            old_name='input_path',
            new_name='input',
        ),
        migrations.RenameField(
            model_name='testcase',
            old_name='output_path',
            new_name='output',
        ),
    ]
