# Generated by Django 4.2.5 on 2023-09-30 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Problem', '0005_rename_input_path_testcase_input_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testcase',
            name='title',
        ),
    ]
